# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SiteHound
email: sitehound@apexa.co.uk
description: > # this means to ignore newlines until "baseurl:"
  SiteHound - easy web analytics tracking.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sitehound.co" # the base hostname & protocol for your site
twitter_username: andyy
github_username:  andyyoung

# Build settings
markdown: kramdown
